### ISSUE TITLE
Issues with RHS PKL map, CAS Planes unable to find either; grid location or laser target.

### ISSUE THREAD

**Issue by EpsilonCommunity** [SceptreOfficial/Simplex-Support-Services#31]
Issues with RHS PKL map, CAS Planes unable to find either; grid location or laser target.

**Comment by SceptreOfficial** [comment]
Sounds like it would be an RHS issue. I'll look into it... but if they're doing special things like they are known to do, it just makes mod compatibility a hassle.

**Comment by SceptreOfficial** [comment]
@EpsilonCommunity does this occur from map click or inputted grid coords (Milsim mode)?

**Comment by EpsilonCommunity** [comment]
Both. Confirmed on both.

**Comment by EpsilonCommunity** [comment]
I thought i was a onclick map error, due to the custom map. Or that the grid coords are wrong somehow.

But neither improved.

Used both modded planes and default settings.

**Comment by SceptreOfficial** [comment]
Map clicked positions work fine on my end. Grid coords are what are failing to get the correct position. The culprit is the CBA function `CBA_fnc_mapGridToPos`. I'll switch over to use `BIS_fnc_gridToPos` since that still seems to work on the map.

**Comment by SceptreOfficial** [comment]
Deleted my previous post.
Map click positions seem to work ok for me, but getting correct grid coords don't work reliably using either `CBA_fnc_mapGridToPos` or `BIS_fnc_gridToPos`. It seems to be an issue with how the map is configured. Grid coordinates are reversed or something, so it is an RHS issue. 

Closing due to 3rd party issue.

**Comment by EpsilonCommunity** [comment]
Thanks for looking into it.
