### ISSUE TITLE
Potential Issue with Simplex & Zeus Enhanced (ZEN)

### ISSUE THREAD

**Issue by dgibso29** [SceptreOfficial/Simplex-Support-Services#61]
We recently included ZEN in our mod pack, and have since had issues with Fixed-wing CAS (CAS Planes consistently fail to acquire target, regardless of target type (smoke, laser, map position, etc)) & Artillery. It works fine on a local server, but breaks on our hosted server. This implies a configuration issue, but we've had no success in resolving it.

Is this a known issue? I've researched the problem but haven't had much success in finding anything. I've started here but I am happy to take this to the ZEN team if it's more likely to be an issue they can resolve.

Thank you.

**Comment by dgibso29** [comment]
I'm unable to replicate this outside of our server, even with our full modpack. Any insight on what could potentially interfere with Simplex is appreciated.

**Comment by SceptreOfficial** [comment]
Not sure how ZEN would interfere with SSS in any way, unless they are modifying the laser target class. I'll do some testing on my dedi and let you know. But, it's probably not ZEN's problem. Are you running ACEX with headless balancing, by chance?

And what issues are you having with artillery? It could be related to the targeting if you're using the 'random dispersion radius'. Otherwise it could be a vanilla issue. Artillery commands aren't very reliable, I've found out.

**Comment by SceptreOfficial** [comment]
Can you do a test without any extra mods loaded? Just SSS, CBA, ACE, and ZEN?

**Comment by dgibso29** [comment]
I agree that it's unlikely to be ZEN. It is only on our radar as it's a recent addition.

We _are_ using ACEX with headless balancing -- known issue?

Artillery issues as reported:
- Not landing at all
- Landing off target
- Landing late (3+ minutes)

I've been unable to replicate them myself off-server.

**Comment by dgibso29** [comment]
> Can you do a test without any extra mods loaded? Just SSS, CBA, ACE, and ZEN?

Already done. It works perfectly.

**Comment by dgibso29** [comment]
Actually, we had issue on a mission that did not have ACEX headless enabled (though it was using the mission maker's own headless balancing), as well as those that do.

**Comment by dgibso29** [comment]
> > Can you do a test without any extra mods loaded? Just SSS, CBA, ACE, and ZEN?
> 
> Already done. It works perfectly.

Apologies -- Not done on the server itself, but on a local server. I will try to arrange for a server-side test with just the basics.

**Comment by SceptreOfficial** [comment]
Headless balancing could break things, so the ACEX fix is already implemented for the next updated. 
I did a local MP test real quick and CAS targeting worked fine from a 2nd connected client. I don't have my dedi updated/set up at the moment so I'll have to test that later.
Artillery has been a headache for awhile. I'm eventually going to make a custom script to handle aiming/firing since the vanilla commands aren't reliable.

**Comment by dgibso29** [comment]
It's worth noting we've been using ACEX headless without (apparent) issues for about 2 months now. That said, I wouldn't be surprised were it the cause.

Do you have a timeline in mind for the next update, or simply "When it's done?"

I'll try to arrange a server test with just the basic mods & will report back.

Thank you!

**Comment by dgibso29** [comment]
@SceptreOfficial We've isolated this issue to ACEX Headless.

**Comment by SceptreOfficial** [comment]
No timeline for the next update, sorry. You can add this line to custom init field on your support(s) to fix the ACEX issue for now:
`(group _this) setVariable ["acex_headless_blacklist",true,true];`

**Comment by dgibso29** [comment]
That'll work until then. Thank you!

**Comment by SceptreOfficial** [comment]
da41e7c8267984452dd918a0d421e72641a29008

**Comment by SceptreOfficial** [comment]
Support vehicles are now automatically blacklisted from the ACE Headless Client balancing system.
