### ISSUE TITLE
RTB option for Gunship

### ISSUE THREAD

**Issue by CommandoCat** [SceptreOfficial/Simplex-Support-Services#65]
A RTB option for the Gunship support would be nice too. Sometimes we're done with the gunship before the timer is up, but because the timer is still running we can't call it on a new location.

**Comment by Mysteryjuju** [comment]
Maybe, the same option should be implemented for CAS Drone support.

**Comment by SceptreOfficial** [comment]
Yeah both systems could definitely be expanded on. I want the option to unlock drones so the UAV terminal can move them around before RTB/de-spawn. I wish the UAV terminal could interact with other vehicles somehow, it would make gunships less rigid as well, because sometimes people want a drone or gunship up indefinitely.

**Comment by SceptreOfficial** [comment]
da41e7c8267984452dd918a0d421e72641a29008

**Comment by SceptreOfficial** [comment]
All supports now have an a "Abort" option. For CAS modules they will RTB and start the cooldown.
